"""BASS V3 (IBASS): searchable cross-branch memory exchange for SISR."""

from .blocks import CIMEX, CIMEXLayer
from .config import (
    ATTENTION_PRIMITIVES,
    CHANNELS,
    CNN_PRIMITIVES,
    EXCHANGE_CONFIGS,
    EXCHANGE_SITES,
    EXCHANGE_STATE_COUNT,
    KERNEL_SIZES,
    REPEATS,
    SEMANTIC_GENOME_LENGTH,
    UNIT_STATE_COUNT,
    WINDOW_SIZES,
)
from .encoding import (
    block_to_state,
    canonical_architecture_count,
    canonical_branch_genomes,
    canonical_exchange_configuration_counts,
    canonicalize_genome,
    decode,
    encode,
    exchange_to_state,
    migrate_v2,
    sample,
    sample_canonical_genome,
    sample_genome,
    state_to_block,
    state_to_exchange,
    to_v2,
    upgrade_v2,
)
from .genotype import (
    ArchitectureSpec,
    BlockGene,
    ExchangeGene,
    canonicalize_architecture,
    canonicalize_branch,
)
from .model_builder import build_ibass_model, build_model, feature_tap_metadata
from .problem import BASSProblem, IBASSProblem
from .repair import repair_architecture, repair_exchange
from .variation import EXCHANGE_MUTATION_WEIGHTS, SEMANTIC_MUTATION_WEIGHTS

__all__ = [
    "ATTENTION_PRIMITIVES",
    "CHANNELS",
    "CIMEX",
    "CNN_PRIMITIVES",
    "EXCHANGE_CONFIGS",
    "EXCHANGE_MUTATION_WEIGHTS",
    "EXCHANGE_SITES",
    "EXCHANGE_STATE_COUNT",
    "KERNEL_SIZES",
    "REPEATS",
    "SEMANTIC_GENOME_LENGTH",
    "SEMANTIC_MUTATION_WEIGHTS",
    "UNIT_STATE_COUNT",
    "WINDOW_SIZES",
    "ArchitectureSpec",
    "BASSProblem",
    "BlockGene",
    "CIMEXLayer",
    "ExchangeGene",
    "IBASSProblem",
    "block_to_state",
    "build_ibass_model",
    "build_model",
    "canonical_architecture_count",
    "canonical_branch_genomes",
    "canonical_exchange_configuration_counts",
    "canonicalize_architecture",
    "canonicalize_branch",
    "canonicalize_genome",
    "decode",
    "encode",
    "exchange_to_state",
    "feature_tap_metadata",
    "migrate_v2",
    "repair_architecture",
    "repair_exchange",
    "sample",
    "sample_canonical_genome",
    "sample_genome",
    "state_to_block",
    "state_to_exchange",
    "to_v2",
    "upgrade_v2",
]
