"""Frozen constants for interaction-aware BASS V3 (IBASS)."""

from bass.v2.config import (
    ATTENTION_PRIMITIVE_CONFIGS,
    ATTENTION_PRIMITIVES,
    BRANCH_COUNT,
    CHANNELS,
    CNN_PRIMITIVE_CONFIGS,
    CNN_PRIMITIVES,
    DEFAULT_HEAD_MODE,
    DEFAULT_INPUT_CHANNELS,
    DEFAULT_SEED,
    DEFAULT_UPSCALE,
    HEADS_BY_CHANNELS,
    KERNEL_SIZES,
    PRIMITIVE_CONFIGS,
    REPEATS,
    UNIT_STATE_COUNT,
    UNITS_PER_BRANCH,
    WINDOW_SIZES,
)

EXCHANGE_SITES = UNITS_PER_BRANCH - 1
EXCHANGE_CONFIGS = (
    ("none", 0),
    ("cimex", 8),
    ("cimex", 16),
)
EXCHANGE_STATE_COUNT = len(EXCHANGE_CONFIGS)
SEMANTIC_GENOME_LENGTH = 1 + BRANCH_COUNT * UNITS_PER_BRANCH + EXCHANGE_SITES

DEFAULT_EXCHANGE_PROBABILITY = 0.5
DEFAULT_CIMEX_GATE = 0.01
CIMEX_MEMORY_RATIO = 0.5
CIMEX_MIN_MEMORY_DIM = 8

__all__ = [
    "ATTENTION_PRIMITIVES",
    "ATTENTION_PRIMITIVE_CONFIGS",
    "BRANCH_COUNT",
    "CHANNELS",
    "CIMEX_MEMORY_RATIO",
    "CIMEX_MIN_MEMORY_DIM",
    "CNN_PRIMITIVES",
    "CNN_PRIMITIVE_CONFIGS",
    "DEFAULT_CIMEX_GATE",
    "DEFAULT_EXCHANGE_PROBABILITY",
    "DEFAULT_HEAD_MODE",
    "DEFAULT_INPUT_CHANNELS",
    "DEFAULT_SEED",
    "DEFAULT_UPSCALE",
    "EXCHANGE_CONFIGS",
    "EXCHANGE_SITES",
    "EXCHANGE_STATE_COUNT",
    "HEADS_BY_CHANNELS",
    "KERNEL_SIZES",
    "PRIMITIVE_CONFIGS",
    "REPEATS",
    "SEMANTIC_GENOME_LENGTH",
    "UNITS_PER_BRANCH",
    "UNIT_STATE_COUNT",
    "WINDOW_SIZES",
]
