"""Compatibility constants; new code should import ``bass.v1`` or ``bass.v2``."""

from .v1.config import (
    BRANCH_COUNT,
    CHANNELS,
    CNN_PRIMITIVES,
    DEFAULT_INPUT_CHANNELS,
    DEFAULT_SEED,
    DEFAULT_UPSCALE,
    KERNEL_SIZES,
    REPEATS,
    UNITS_PER_BRANCH,
)
from .v1.config import DECODED_VALUES as V1_DECODED_VALUES
from .v1.config import GENOME_BITS as V1_GENOME_BITS
from .v2.config import ATTENTION_PRIMITIVES, HEADS_BY_CHANNELS, WINDOW_SIZES
from .v2.config import LEGACY_GENOME_BITS as V2_GENOME_BITS
from .v2.config import SEMANTIC_GENOME_LENGTH as V2_SEMANTIC_GENOME_LENGTH

__all__ = [
    "ATTENTION_PRIMITIVES",
    "BRANCH_COUNT",
    "CHANNELS",
    "CNN_PRIMITIVES",
    "DEFAULT_INPUT_CHANNELS",
    "DEFAULT_SEED",
    "DEFAULT_UPSCALE",
    "HEADS_BY_CHANNELS",
    "KERNEL_SIZES",
    "REPEATS",
    "UNITS_PER_BRANCH",
    "V1_DECODED_VALUES",
    "V1_GENOME_BITS",
    "V2_GENOME_BITS",
    "V2_SEMANTIC_GENOME_LENGTH",
    "WINDOW_SIZES",
]
